train_batch_size = 4
time_out = 2400
number_of_intervals = 10
number_of_classes = number_of_intervals + 2
device = "cuda"
epochs = 31
k_fold = 3
alphabet_length = 12
number_of_solvers = 11
number_of_predictions = 10
learning_rate = 0.00005
weight_decay = 5e-4